### ISSUE TITLE
(S)Figure out what to do with FAS accounts that have no full name attached to them

### ISSUE THREAD

**Issue by sfinn85** [fedora-infra/freeipa-fas#11]
**Acceptance Criteria:**

- Find out how many ppl only have one name
- Identify next possible steps to resolve this issue.

**DOD:**

- All above complete. Reaching out on IRC daily to discuss next steps

**Overview of thoughts:**
IPA wants a firstname and last name. In most cases, we can split and roughly approximate these things, and use fas's human_name as the display/full name.

But a lot of accounts in fas don't even have a name attached to them at all.
We need to figure out what to do for the following cases when we go to import:

User has no name at all in FAS
User has only one word as their name (as IPA wants both a first and last name)
 
We can default values for these (they can't be blank), but that seems odd.

**Comment by tiran** [comment]
LDAP schema only enforces the presence of ``sn`` (surname, family name). ``givenname`` (first name) is optional in LDAP.

IPA plugin code enforces ``givenname`` as a required attribute. Code that it is always set and present as a non-empty value. It's not easily possible to lift the restriction.

**Comment by sfinn85** [comment]
Hi @relrod 

How are we getting on with this one? Can you add a short update here, when you get a chance, thanks a mill

**Comment by relrod** [comment]
`{'hastab': 0, 'hasspaceandtab': 0, 'none': 5548, 'splitnoargslen': {1: 5973, 2: 26313, 4: 899, 3: 3488, 5: 148, 6: 20, 7: 1, 0: 1, 8: 1}}`

Breaking this down:

* `hastab` and `hasspaceandtab` being 0 is good, it means we likely only allow spaces between name components in FAS, yay.
* `none` - this means there are currently 5548 accounts with no name attached to them at all.
* `splitnoargslen` is the length returned on a `len()` of `split()`ing the name without passing `split` any args (so just the default splitting rules). It's a hash keyed on the **length** with values of how many accounts have each length. e.g. 5973 accounts have only one word for their name. 26313 have two words. 1 has zero words (curious about that one and why it's `""` and not `None` like the rest). 1 has eight words. etc.

**Comment by relrod** [comment]
I just had a realization here, these stats are bad.

I am not in the `accounts` group, so anyone with privacy enabled in FAS shows up as having no name attached to the account. I'll either have to poke the db directly or ask for `accounts` access, possibly in stg for now.

**Comment by relrod** [comment]
Okay. So this has become less of a concern now, or at least a different concern:

```
rick@localhost 92% ~/dev/etc$ python3 fas_name_stats.py 
{'none': 0, 'tabs': 0, 'tabsandspaces': 0, 'splitnoargslen': {1: 6362, 2: 30458, 4: 1012, 3: 4009, 5: 164, 7: 1, 6: 20, 0: 3, 8: 1}}
```

The reason for my original concern (about accounts with no name attached to them) was simply because I wasn't seeing them due to not being in `accounts`, I didn't think about that until yesterday. I've been added to that group in staging, and reran the scripts and the stats look way better.

So current concerns here that we need to figure out:

* Accounts that legitimately have no name on them (there are **2** that have a single space for their name (**1** of those is marked inactive), and **1** that has an empty string, somehow).
* Accounts that have one word names attached to them. There are **~6300** of them.
* Accounts that have >2 word names attached to them. IPA wants a first and last name (as far as I know). So do we split on the first word and take everything else as the last name? That seems less-than-correct, but I'm not sure what other options to consider here.

**Comment by sfinn85** [comment]
Investigate what we need to do here.

**Comment by tiran** [comment]
I'm currently investigation if it's possible to make given name optional.

**Comment by sfinn85** [comment]
Thanks @tiran  any updates?

**Comment by StephenCoady** [comment]
@relrod to practice KISS here, what about we reach out to the 2 outliers and ask them to correct their name or provide a name - is that an option? For the >2 words I think something like what you suggested sounds as good as we will get. We could also just ignore everything after the 2nd to keep it even simpler.

For the one word user names we could add some standard string set for either first or last. I don't see another option here unless we wait to see if @tiran can easily make given name optional.

**Comment by sfinn85** [comment]
Thanks @StephenCoady for your thoughts on this. I think we need to make a decision on this approach soon to move forward. @relrod what are your thoughts here?

**Comment by sfinn85** [comment]
Move to in progress, lets look at getting an email out to all highlighting or to two members.

**Comment by StephenCoady** [comment]
As per the discussion on sprint planning session I am putting forward a solution so we can move this small task on. 

> Accounts that legitimately have no name on them

I think we should reach out to these 3 users and give them plenty of time to change their name. Failing that we just manually insert a temporary name that they can change.

> Accounts that have one word names attached to them

We use the one name they have provided and use an arbitrary string for the other name. i.e. `John` becomes `User John`

> Accounts that have >2 word names attached to them

I think we should take the first complete string as their first name and everything else as their second name.

Like I said I have no real investment in these options but we do need to decide.

**Comment by sfinn85** [comment]
Thanks @StephenCoady .  I will flag in mail going out later to gain feedback.

**Comment by abompard** [comment]
Sounds good to me, Stephen.

**Comment by tiran** [comment]
> Thanks @tiran any updates?

My experimental patches were partly successful. I'm now at a point where web UI acts funny and is partly broken. The rabbit hole is getting deeper and the patch larger.

I'm going to discuss the issue with IPA team and check if it makes sense to develop a proper fix in IPA upstream.

**Comment by sfinn85** [comment]
Daily stand up update:
@StephenCoady updated that @tiran  seems to be working on this. 

From my understanding, @abompard  I think we need to reach out to Tiran to gain an understanding of what is being worked on and what is needed to ensure this user story is completed for the AAA project. @tiran  would you like to catch up on a call later or on IRC to discuss this?

**Comment by sfinn85** [comment]
Hi all, we need to move this on and make a decision. 
We have two options:
1. We stick with @tiran  approach, which sounds good for a overall IPA solution but we could remain blocked for quite some time, as it will take time out to resolve some issues he has come against and the timeline on when this will be done is out of our control. Thanks for your time on this @tiran .
2. We remove the mandatory need for first name, last name from the system. @StephenCoady  as set aside time to do this. 

My recommendation at this point and with the tight deadline on this project and with the requirement to only find a solution for AAA is to move forward with option 2. As Tech Lead @abompard can you make this decision on our stand up tomorrow to allow us to move forward?

Thanks a mill
Sarah

**Comment by tiran** [comment]
There is a simpler workaround. You could use a magic marker for the given name, put the entire name from the old FAS system as surname, full name, display name and GECOS. You have to set full name (cn), display name and GECOS explicitly as they are auto-filled from given name and surname.

```
ipa user-add --first='<Fnu>' --last=$NAME --cn=$NAME --displayname=$NAME --initials='' --gecos=$NAME
```

A common magic marker makes it easy to find migrated users later.

(Fnu is the official acronym for first name unknown)

**Comment by sfinn85** [comment]
Need to let the users know through email. Another user story created #103. So this is complete as we have identified a solution . Good to go with a solution @abompard
