### ISSUE TITLE
(L) As a AAA developer I want a local development environment so that I can easily develop on my laptop

### ISSUE THREAD

**Issue by sfinn85** [fedora-infra/freeipa-fas#13]
**Acceptance Criteria**
================
1. It is possible to run the application and test from a local environment (venv, vagrant, container)
2. Changes made to the code base automatically update the running application
3. Dependencies are managed following the best practice (poetry)
4. It is easy to build and release the application.
5. Create data generation script to test 

**Definition of Done:**

- All the above completed
- Reviewed by team member

**Comment by StephenCoady** [comment]
Can't currently assign issues but noting here that I am working on this.

**Comment by sfinn85** [comment]
Hi @StephenCoady  you have probably updated us on IRC stand up, how this is going but can you pop a short update in here.. thanks a mill

**Comment by StephenCoady** [comment]
I would say close to complete. Some small house keeping and improvements left to do on https://github.com/fedora-infra/securitas/pull/73 and my linked PR but nothing major.

**Comment by StephenCoady** [comment]
Update.

As of now, the acceptance criteria of this user story have been met. The last remaining PR is currently in review and once that is merged this user story can be closed.

**Comment by sfinn85** [comment]
Great thanks for the update @StephenCoady , great work but lets leave this open until then. I will move it back to in progress. Going forward let's see if we can identify at the planning session, user stories that have multiply parts, dependencies. We can then break these down into smaller user story and only pull in a user story that can be completed within that sprint. In this case, we would of pulled this user story in but created another user story for the PR piece to pulled into Sprint 2.

**Comment by StephenCoady** [comment]
Not sure this is blocked. The final PR to complete this card is being reviewed.
