### ISSUE TITLE
(L) As a AAA developer I want Continuous Integration to run on each PR so that new code meets a certain standard

### ISSUE THREAD

**Issue by sfinn85** [fedora-infra/freeipa-fas#14]
**Acceptance Criteria
=**===============

1. Continuous Integration is using the tox tool to orchestrate steps.
2. Code base complies with PEP8 (flake8)
3. Code base is uniformly formatted (black)
4. Code base is secured (bandit)
5. Dependencies licences are checked (liccheck)
6. Dummy tests ( Unit & Integration) to make sure they are run in CI
7. Unit tests and coverage are run
7. Integration tests are run.

**DOD:** 
All above completed

**Comment by abompard** [comment]
This was filed against the wrong project, the correct issue is [securitas#63](https://github.com/fedora-infra/securitas/issues/63).
