### ISSUE TITLE
(M/L) As a AAA developer I want Continuous Deployment to the staging environment so that I can easily test/demo new features

### ISSUE THREAD

**Issue by sfinn85** [fedora-infra/freeipa-fas#15]
**Acceptance Criteria**
================

1. Openshift project is created in staging
2. Configuration and Secrets are managed in ansible
3. Application is build from git
4. Every commit on the staging branch triggers a new build and deployment in OpenShift

**DOD:**

- All AC completed above
- Team review

**Comment by puiterwijk** [comment]
Given that this project involves an IPA schema extension, automatically releasing/merging should NOT be done for this project.

**Comment by abompard** [comment]
Hey Patrick, could you elaborate on that? This is about the portal (a flask app) being CD enabled, and in my understanding an update to the portal is not going to change anything in the IPA schema extension (since it's only using the IPA API).

**Comment by abompard** [comment]
Ah, the ticket was filed in the wrong project, it should in the fas-ng project (the portal).
