### ISSUE TITLE
(S) As a AAA developer I want to have Contribution Guidelines and Developer documentation so that it is easy to contribute to my project

### ISSUE THREAD

**Issue by sfinn85** [fedora-infra/freeipa-fas#17]
Note dependency: 13,14 need to happen first.

Acceptance Criteria
================

1. Project contains documentation that describe how to setup the development environment
2. Project contains documentation that describe how to run the CI
3. Project contains documentation that describe how to contribute

**DOD:** 
All above completed
Reviewed

**Comment by ryanlerch** [comment]
Filed this issue in the correct location.

https://github.com/fedora-infra/securitas/issues/65
