### ISSUE TITLE
Support registering more than one IRC nick, SSH key, and GPG key per FAS user

### ISSUE THREAD

**Issue by Conan-Kudo** [fedora-infra/freeipa-fas#8]
(**Note: this was originally filed as https://github.com/fedora-infra/fas/issues/205 and later as https://github.com/fedora-infra/noggin/issues/8**)

The current FAS only lets you register one IRC nick per user account. However, I personally use multiple SSH and GPG keys, different IRC nicks from time to time, and it would be great if that information could be represented in FAS.

My [Launchpad account](https://launchpad.net/~ngompa13) represents this information fairly well, but my FAS account does not. I would love it if FAS could represent this information, as I use it way more than my Launchpad account.

It may also be a good idea to support multiple email addresses, to deal with the multiple roles so that BZ accounts can successfully bind to FAS accounts.

For example, I have a corporate email address and a personal one. I prefer my personal one, but some aspects of Fedora activities occur under the auspices of my employer, and thus go under my corporate email address.

This is much more common with Red Hat employees that have RHAS accounts that can be used with Red Hat Bugzilla along with their personal FAS accounts. Being able to register those will allow [hacks like this](https://infrastructure.fedoraproject.org/cgit/ansible.git/tree/roles/distgit/pagure/files/fas2.py#n149) to go away entirely.

**Comment by tiran** [comment]
Some issues are going to go away:

* Email address and ssh key are provided by FreeIPA default schema. Both are already multi-valued.
* The new FAS plugin for FreeIPA adds dedicated fields for RHBZ email address, Github, and Gitlab account. The ``bugzilla_email`` hack won't be necessary any more. Pagure account is tight to the user name (uid). All four fields are single-valued.
* GPG key id is multi-valued. I reserved enough space for long PGP key ids.
* IRC nick is currently single-valued and plain text. It's trivial to make it multi-valued. There is currently no schema to encode an IRC network. Is it useful to support other networks than freenode?

There is currently not much additional verification of fields. The plugin just checks that a non-empty ``fasrhbzemail`` attribute must contain an ``@``.

The FreeIPA schema and FreeIPA plugin definition does not enforce the presence of an email address. It's possible to remove all email addresses from a user. There is also no concept of primary email address.

**Comment by tiran** [comment]
If FAS requires a primary email address, then I have to add another field. It's not possible to use the first entry of the mail field as primary address. LDAP does not guarantee that multi-valued attributes retain order.

**Comment by Conan-Kudo** [comment]
> IRC nick is currently single-valued and plain text. It's trivial to make it multi-valued. There is currently no schema to encode an IRC network. Is it useful to support other networks than freenode?

Yes. This is especially useful when people wind up having different nicks on different networks because those networks have restrictions (for example, some of my nicks used on Freenode are not valid on OFTC because they are too long there)

**Comment by Conan-Kudo** [comment]
@tiran Any chance this is happening anytime soon?
