### ISSUE TITLE
Support the validation of email

### ISSUE THREAD

**Issue by abompard** [fedora-infra/freeipa-fas#86]
In fedora-infra/noggin#184, it has been requested that emails are validated (by sending a token) before accounts are considered active. Here's what I thought of so far:
- we add a `fasPendingEmail` multi-valued field where users add their emails
- the `mail` attribute becomes only writable by admins
- Noggin sends an email, validates the clicked link, and moves addresses from `fasPendingEmail` to `mail` with the admin account.
- we use the `fasStatusNote` field as an indication that the account is active, for example with pre-defined values such as `ACTIVE`, `PENDING_EMAIL_VALIDATION`, `PENDING_FPCA`, ...
- in fasjson, the API that apps will be using, we don't only return that have `fasStatusNote == 'ACTIVE'`.

@tiran , a few questions:
- does this sound sane/feasible to you? Do you have suggestions?
- Is it even possible to make the `mail` attribute admin-writable only? Could we make it admin-only to add but user-allowed to remove?
- I don't think the `fasStatusNote` field is indexed at the moment so it was probably not indented for this usage, should we add another one that would be more appropriate?

Thanks!

**Comment by tiran** [comment]
- Yes, it is feasible. I would create a permission and privilege for access to these fields, though.
- You have to remove the permission ``selfservice:Users can manage their own email address``, which was introduced in commit fd3645a7bff2984d5ef5b0218fdf626bcf1a22ec
- You cannot easily give separate permissions for adding and removing attributes. Both operations are controlled by write permission. Self-removal of groups uses a trick that does not work for mail addresses.
- It's easy to add an index for status note.

**Comment by tiran** [comment]
By the way IPA has the concept of stage user, https://www.freeipa.org/page/V4/User_Life-Cycle_Management#stageuser_plugin

**Comment by abompard** [comment]
We will use stage users.
