### ISSUE TITLE
License clarification: GPLv3 or GPLv3+?

### ISSUE THREAD

**Issue by Conan-Kudo** [fedora-infra/freeipa-fas#98]
There's no per-file license headers on this project, so I cannot figure out whether this is GPLv3 or GPLv3+. Could you please clarify it in the project?

**Comment by tiran** [comment]
The license of the project is in the COPYING file. It's the same as [FreeIPA](https://www.freeipa.org/page/License) license: GPLv3.

**Comment by Conan-Kudo** [comment]
FreeIPA is GPLv3+, per the license headers that exist within the source tree. I can't tell in this project, which is why I asked.

**Comment by abbra** [comment]
It is GPLv3+, quite clear from the actual commit that updated the licensing:

```
$ git log COPYING
commit 7493d781dfcaa7995f7864a09ad39ba6a89f1a9c
Author: Jakub Hrozek <jhrozek@redhat.com>
Date:   Thu Dec 9 13:59:11 2010 +0100

    Change FreeIPA license to GPLv3+
    
    The changes include:
     * Change license blobs in source files to mention GPLv3+ not GPLv2 only
     * Add GPLv3+ license text
     * Package COPYING not LICENSE as the license blobs (even the old ones)
       mention COPYING specifically, it is also more common, I think
    
     https://fedorahosted.org/freeipa/ticket/239
```

**Comment by Conan-Kudo** [comment]
@abbra I might have mis-spoken previously. I meant that I knew that FreeIPA is GPLv3+ because the sources clearly indicate it. The problem is that _this project_ does not have a clear indicator of whether it is GPLv3 or GPLv3+.

(As an aside, I'm sick of seeing the standard suggested license header in the GNU licenses being removed from projects, it makes life considerably more difficult for understanding what kind of licensing a project has)

**Comment by abbra** [comment]
I think a common approach for quite few years now is to rely on licensing in the repo and git commit history. I saw many projects doing that routinely. I wonder if license-scanning tools support this approach, though.

**Comment by Conan-Kudo** [comment]
@abbra None of the ones I use do, at least. And none of the tools used for package reviews do either.

**Comment by abbra** [comment]
Best overview about the approaches that I am aware of is still https://softwarefreedom.org/resources/2012/ManagingCopyrightInformation.html. It basically lists both file-scoped and centralized ones, with bare-bone per-file notices.

**Comment by tiran** [comment]
Fixed in https://github.com/fedora-infra/freeipa-fas/commit/22150ee9ad6397df591f10ffd839ce2dde2f2391

**Comment by Conan-Kudo** [comment]
@tiran Thanks!
